version: "3.2"
services:
  phpmyadmin5.6:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mysql-5.6-localhost7778
    environment:
      - PMA_HOST=192.168.1.2
    external_links:
      - mysql5.6-192.168.1.2:db
    ports:
      - "7778:80"
    restart: always