version: "3.2"
services:
  mysql5.6:
    image: mysql:5.6
    container_name: mysql5.6-172.28.5.1
    volumes:
      - your_absolute_local_directory:/var/lib/mysql
    networks:
       default:
          ipv4_address: 172.28.5.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
  default:
    external:
      name: devnetwork